artifacts_root : artifacts


data_ingestions:
  root_dir: artifacts/data_ingestion
  source_URL : https://drive.google.com/file/d/1ABaDnYiccGI0VWzcPiLH9SFODmqpZovd/view?usp=sharing
  local_data_file : artifacts/data_ingestions/data.zip
  unzip_dir : artifacts/data_ingestion